{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: {{ required "cloudflare.apiToken is required when cloudflare.existingSecret is not set" .Values.cloudflare.apiToken | quote }}
{{- end }}
